bar_components:
  default: >-
    [{"component_name":"big-a","route":"discovery","position":"left"},
     {"component_name":"big-b","route":"discovery","position":"left"},
     {"component_name":"big-c","route":"discovery","position":"right-alt"},
     {"component_name":"big-d","route":"discovery","position":"right-alt"},
     {"component_name":"big-e","route":"discovery","position":"top"},
     {"component_name":"big-f","route":"discovery","position":"top"},
     {"component_name":"big-c","route":"topic","position":"right"},
     {"component_name":"big-d","route":"topic","position":"right"},
     {"component_name":"big-e","route":"topic","position":"top"},
     {"component_name":"big-a","route":"categories","position":"left"},
     {"component_name":"big-c","route":"category","position":"left"},
     {"component_name":"big-b","route":"tag","position":"right"}]
  json_schema: >-
    {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "component_name": {
            "type": "string"
          },
          "route": {
            "type": "string"
          },
          "position": {
            "type": "string"
          }
        }
      }
    }
  description: "Specify Component, Route and Position.  Order determines layout. <br/><br/>Route must be either: discovery, topic, tag, category OR categories.  <br/><br/>Position must be either: top, left, right OR right-alt."
left_sidebar_width:
  default: 300
right_sidebar_width:
  default: 300
sticky_sidebars:
  default: true
sidebar_sticky_top_position:
  default: 60
sidebar_height:
  default: 800
scrolly_sidebars:
  default: false
top_bar_height:
  default: 150
top_bar_sticky_top_position:
  default: 60
sidebar_gap:
  default: 5
